services:
  - type: web
    name: finance-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SPENDING_ALERT_PCT
        value: "80"
      - key: APP_ENV
        value: production
      - key: STORAGE_ENDPOINT
        value: ""
      - key: SMTP_HOST
        value: ""
      - key: PORT
        value: "8080"
      - key: CORS_ORIGINS
        value: "https://finance-frontend-3tf6.onrender.com"
    healthCheckPath: /api/v1/health

  - type: web
    name: finance-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npx serve -s dist/dsfr-finance/browser -l 4200
    plan: free
    envVars:
      - key: NODE_VERSION
        value: "20"
