ALTER TABLE patrimony_snapshots
  ADD COLUMN IF NOT EXISTS variation_pct DECIMAL(8,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS variation_val DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rentability   DECIMAL(8,4) NOT NULL DEFAULT 0;
